### ISSUE TITLE
git -C <path> causing issues in RHEL7

### ISSUE THREAD

**Issue by gepandz** [mpalmer/git-version-bump#11]
Hi! I'm trying to use this gem in my RHEL7 environment, which is running git version 1.8.3.1. I don't see where the -C option is implemented in that version of git, and it looks like the error is falling through some cracks to be caught by your "This should never happen" error.

Here is the basic info for my repo and the error I'm seeing:

``` bash
> git tag
0.1.0
v0.1.1
> git version-bump -h; # Show that git can find the script and gem in my $PATH fine
Usage: git version-bump [-n|--notes] <major|minor|patch|show>
<snip>
> git version-bump show
/path/to/my/home/.gem/ruby/gems/git-version-bump-0.15.1/lib/git-version-bump.rb:285:in `gem_version': Unable to determine version from local git repo.  This should never happen. (GitVersionBump::VersionUnobtainable)
        from /path/to/my/home/.gem/ruby/gems/git-version-bump-0.15.1/lib/git-version-bump.rb:37:in `version'
        from /path/to/my/home/.gem/ruby/gems/git-version-bump-0.15.1/bin/git-version-bump:38:in `<top (required)>'
        from /path/to/my/home/bin/git-version-bump:23:in `load'
        from /path/to/my/home/bin/git-version-bump:23:in `<main>'
```

I get the same error with major, minor, and patch, as well.

I think the issue was introduced in v0.11.0. Basically, it looks like the system() call fails on line 36 (based on current v0.15.1), and the `$? == 0` check falls into the gem_version(use_local_git), which has use_local_git as true, and is caught in the "This should never happen" section on lines 285-286.

Am I missing a really obvious workaround, or does the code need to change to support older versions of git? I'm working at an enterprise, so the probability of moving to git version 2.9.2 is ... slim. :confused: 

Thanks!

**Comment by gepandz** [comment]
Out of curiosity, I just removed the offending option and it worked for me (once I realized that the tags required annotations... :confounded:). Ye olde vim substitution for the winne: `:%s/-C #{sq_git_dir} //g` :smile: 

One option may be to include the `-C` into the value of #{sq_git_dir} and approach that option as a unit. Not pretty, but it *should* be effective.
